#755 Circle-CI: Try experimental auto memory limit in docker containers

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,7 +27,7 @@ jobs:
               name: E2E tests
               command: |
                 export SCENARIOO_DATA=./scenarioo-docu-generation-example/build/scenarioDocuExample
-                java -Xms1024m -Xmx1024m -jar scenarioo-server/build/libs/scenarioo-latest.war > scenarioo-server.log || echo "Process died $?" >> scenarioo-server.log &
+                java -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -jar scenarioo-server/build/libs/scenarioo-latest.war > scenarioo-server.log || echo "Process died $? see https://circleci.com/blog/how-to-handle-java-oom-errors/" >> scenarioo-server.log &
                 export PROTRACTOR_BASE_URL=http://localhost:8080/scenarioo
                 export BRANCH="$CIRCLE_BRANCH"
                 sleep 30  # Give server some time because of comparisons
