#755 Circle-CI: Disable gradle deamon for CI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -15,13 +15,13 @@ jobs:
           - checkout
           - run:
               name: Clean & install
-              command: ./gradlew clean build -x test
+              command: ./gradlew clean build -x test --no-daemon
           - run:
               name: Unit tests
-              command: ./gradlew test -x scenarioo-client:npm_test --continue
+              command: ./gradlew test -x scenarioo-client:npm_test --continue --no-daemon
           - run:
               name: JS tests
-              command: ./gradlew scenarioo-client:npm_test
+              command: ./gradlew scenarioo-client:npm_test --no-daemon
               when: always
           - run:
               name: E2E tests
@@ -32,7 +32,7 @@ jobs:
                 export BRANCH="$CIRCLE_BRANCH"
                 sleep 30  # Give server some time because of comparisons
                 export GRADLE_OPTS="-Xms300m -Xmx300m"
-                ./gradlew scenarioo-client:runE2eCircleCi || echo "E2E gradle died. Exit code: $? see https://circleci.com/blog/how-to-handle-java-oom-errors/" >> scenarioo-server.log
+                ./gradlew scenarioo-client:runE2eCircleCi --no-daemon || echo "E2E gradle died. Exit code: $? see https://circleci.com/blog/how-to-handle-java-oom-errors/" >> scenarioo-server.log
           - store_artifacts:
               path: scenarioo-server.log
           - store_artifacts:
