#755 Circle-CI: Simplify artifact handling. Fix E2E reporting

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -15,7 +15,9 @@ jobs:
           - checkout
           - run:
               name: Clean & install
-              command: ./gradlew clean build -x test --no-daemon
+              command: |
+                mkdir -p test-results
+                ./gradlew clean build -x test --no-daemon
           - run:
               name: Unit tests
               command: ./gradlew test -x scenarioo-client:npm_test --continue --no-daemon
@@ -26,18 +28,14 @@ jobs:
           - run:
               name: E2E tests
               command: |
-                ./gradlew --stop
                 export SCENARIOO_DATA=./scenarioo-docu-generation-example/build/scenarioDocuExample
-                java -Xms800m -Xmx800m -jar scenarioo-server/build/libs/scenarioo-latest.war > scenarioo-server.log || echo "Scenarioo server died. Exit code: $? see https://circleci.com/blog/how-to-handle-java-oom-errors/" >> scenarioo-server.log &
+                java -Xms800m -Xmx800m -jar scenarioo-server/build/libs/scenarioo-latest.war > test-results/scenarioo-server.log || echo "Scenarioo server died. Exit code: $? see https://circleci.com/blog/how-to-handle-java-oom-errors/" >> test-results/scenarioo-server.log &
                 export PROTRACTOR_BASE_URL=http://localhost:8080/scenarioo
+                export SCENARIOO_TARGET_DIRECTORY="./test-results/e2eScenariooDocumentation"
                 export BRANCH="$CIRCLE_BRANCH"
                 sleep 30  # Give server some time because of comparisons
                 export GRADLE_OPTS="-Xms300m -Xmx300m"
-                ./gradlew scenarioo-client:runE2eCircleCi --no-daemon || echo "E2E gradle died. Exit code: $? see https://circleci.com/blog/how-to-handle-java-oom-errors/" >> scenarioo-server.log
-          - store_artifacts:
-              path: scenarioo-server.log
-          - store_artifacts:
-              path: scenarioo-client/scenariooDocumentation
+                ./gradlew scenarioo-client:runE2eCircleCi --no-daemon
           - run:
               name: Collect test results
               command: |
